feat: support expiring applications
Basis-Theory/basistheory-swift pull request #7
Opened 2022-11-16 22:06 UTC by jleon15

## Description

- Support expiring applications by adding expires_at and can_create_expiring_applications flag. 

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-11-18 20:50 UTC, kevinperaza commented on BasisTheory/APIs.swift
> +    public static var basePath = "https://api-dev.basistheory.com"
I don't think this should target dev?

2022-11-18 20:50 UTC, brigonzalez commented on BasisTheory.podspec
> +  s.source = { :git => 'git@github.com:Basis-Theory/basistheory-swift.git', :tag => '0.0.1' }
this needs to be reverted

2022-11-18 20:50 UTC, brigonzalez commented on BasisTheory/APIs.swift
> +    public static var basePath = "https://api-dev.basistheory.com"
default should be prod

2022-11-19 01:59 UTC, dhudec requested changes

2022-11-19 01:59 UTC, dhudec commented on .openapi-generator/VERSION
> +6.3.0-SNAPSHOT
We need to pin this version in the script too. I will do this on Monday, don't worry about it and enjoy the time off.

2022-11-21 14:36 UTC, dhudec approved these changes

2022-11-21 15:03 UTC, kevinperaza approved these changes

2022-11-21 15:58 UTC, merged